# Generated by Django 5.1.7 on 2025-03-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.club'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
